DROP TYPE IF EXISTS rolelist;

CREATE TYPE rolelist AS ENUM (
  'Warrior',
  'Thief',
  'Brute',
  'Mage',
  'Hunter',
  'Bard'
);

CREATE TABLE characters (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  level INTEGER NOT NULL,
  role rolelist NOT NULL,
  hp INTEGER NOT NULL,
  strength INTEGER NOT NULL,
  dexterity INTEGER NOT NULL,
  constitution INTEGER NOT NULL,
  intelligence INTEGER NOT NULL,
  wisdom INTEGER NOT NULL,
  charisma INTEGER NOT NULL,
  imageURL TEXT not null
);